### PR TITLE
Redact addressLine and dependentLocality from billingAddress

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #???

The following tasks have been completed:

 * [x] Confirmed there are no ReSpec errors/warnings.
 * [ ] Added Web platform tests (link)
 * [ ] added MDN Docs (link)

Implementation commitments:

 * [ ] Safari (link to issue)
 * [ ] Chrome (link to issue)
 * [ ] Firefox (link to issue)
 * [ ] Edge (public signal)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-method-basic-card/pull/67.html" title="Last updated on Mar 12, 2019, 10:28 PM UTC (e30d0b4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-method-basic-card/67/cb06797...e30d0b4.html" title="Last updated on Mar 12, 2019, 10:28 PM UTC (e30d0b4)">Diff</a>

### CODE REVIEW

**Review by ianbjacobs — COMMENTED** [review]
Thanks @marcoscaceres. I think we should wait to hear back from @aestes before merging with "dependentLocality".

Ian

**Comment by ianbjacobs** [comment]
Hi @marcoscaceres,

We need more discussion before making redactList normative. I don't yet know whether that is supported by other implementers. Also, MAY browsers redact more for privacy? If so, does that mean they don't conform?

**Comment by rsolomakhin** [comment]
FWIW, Chrome plans to implement `redactList`.

**Review by rsolomakhin — COMMENTED** [review]
Regarding the conversation about the `dependentLocality`, I'm not aware of any countries where tax varies based on this granularity, but if another implementer requires this field, than I would be OK keeping it in `billingAddress`.

**Review by ianbjacobs — APPROVED** [review]

**Pull request merged**
