### PR TITLE
 Add text about why the api can reduce need to store credit card information

### PR DESCRIPTION
**Pull request by adamroach**
Updated PR to address https://github.com/w3c/webpayments-methods-card/issues/16

### CODE REVIEW

**Comment by ianbjacobs** [comment]
@adamroach,

I cannot find recent discussion of this pull request. But I'd like to propose that we not incorporate it into the specification, and instead move it to FAQ on the developer portal:
 https://github.com/w3c/payment-request-info/wiki/FAQ

Specifically, I am thinking of adding it as additional context to this question:
 
  How does Payment Request API affect PCI/DSS compliance?
  https://github.com/w3c/payment-request-info/wiki/FAQ#how-does-payment-request-api-affect-pcidss-compliance

Please let me know if that's ok with you and I'll edit the FAQ and close this PR. Thanks!

Ian

**Comment by ianbjacobs** [comment]
@admroach,

I went ahead and added text to give a clearer sense of my proposal:
 https://github.com/w3c/payment-request-info/wiki/FAQ#what-is-the-impact-of-the-apis-on-merchant-side-storage-of-payment-credentials

I think it's a good fit in the dev portal.

Ian

**Comment by marcoscaceres** [comment]
I'll migrate this to the intro, actually. This is good text to put there.

**Comment by marcoscaceres** [comment]
This is now https://github.com/w3c/payment-method-basic-card/pull/42

**Pull request closed without merging**
